# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170521_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=product.models.product_image_path),
        ),
    ]
