# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20170522_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='seller',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
